<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokerhands.proto

namespace PokerHands;

if (false) {
    /**
     * This class is deprecated. Use PokerHands\BestHandResult\ResultCard\Rank instead.
     * @deprecated
     */
    class BestHandResult_ResultCard_Rank {}
}
class_exists(BestHandResult\ResultCard\Rank::class);
@trigger_error('PokerHands\BestHandResult_ResultCard_Rank is deprecated and will be removed in the next major release. Use PokerHands\BestHandResult\ResultCard\Rank instead', E_USER_DEPRECATED);

