<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokerhands.proto

namespace PokerHands;

if (false) {
    /**
     * This class is deprecated. Use PokerHands\BestHandResult\ResultCard\Suit instead.
     * @deprecated
     */
    class BestHandResult_ResultCard_Suit {}
}
class_exists(BestHandResult\ResultCard\Suit::class);
@trigger_error('PokerHands\BestHandResult_ResultCard_Suit is deprecated and will be removed in the next major release. Use PokerHands\BestHandResult\ResultCard\Suit instead', E_USER_DEPRECATED);

