<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokerhands.proto

namespace PokerHands;

if (false) {
    /**
     * This class is deprecated. Use PokerHands\BestHandResult\ResultCard instead.
     * @deprecated
     */
    class BestHandResult_ResultCard {}
}
class_exists(BestHandResult\ResultCard::class);
@trigger_error('PokerHands\BestHandResult_ResultCard is deprecated and will be removed in the next major release. Use PokerHands\BestHandResult\ResultCard instead', E_USER_DEPRECATED);

