<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokerhands.proto

namespace PokerHands;

if (false) {
    /**
     * This class is deprecated. Use PokerHands\BestHandResult\Category instead.
     * @deprecated
     */
    class BestHandResult_Category {}
}
class_exists(BestHandResult\Category::class);
@trigger_error('PokerHands\BestHandResult_Category is deprecated and will be removed in the next major release. Use PokerHands\BestHandResult\Category instead', E_USER_DEPRECATED);

