<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokerhands.proto

namespace PokerHands;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PokerHands.BestHandResult</code>
 */
class BestHandResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.PokerHands.BestHandResult.Category category = 1;</code>
     */
    private $category = 0;
    /**
     * Generated from protobuf field <code>repeated .PokerHands.BestHandResult.ResultCard cards = 2;</code>
     */
    private $cards;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $category
     *     @type \PokerHands\BestHandResult\ResultCard[]|\Google\Protobuf\Internal\RepeatedField $cards
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pokerhands::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.PokerHands.BestHandResult.Category category = 1;</code>
     * @return int
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Generated from protobuf field <code>.PokerHands.BestHandResult.Category category = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCategory($var)
    {
        GPBUtil::checkEnum($var, \PokerHands\BestHandResult_Category::class);
        $this->category = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .PokerHands.BestHandResult.ResultCard cards = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCards()
    {
        return $this->cards;
    }

    /**
     * Generated from protobuf field <code>repeated .PokerHands.BestHandResult.ResultCard cards = 2;</code>
     * @param \PokerHands\BestHandResult\ResultCard[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCards($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \PokerHands\BestHandResult\ResultCard::class);
        $this->cards = $arr;

        return $this;
    }

}

