<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokerhands.proto

namespace PokerHands;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PokerHands.HandRequest</code>
 */
class HandRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .PokerHands.HandRequest.HandCard cards = 1;</code>
     */
    private $cards;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \PokerHands\HandRequest\HandCard[]|\Google\Protobuf\Internal\RepeatedField $cards
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pokerhands::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .PokerHands.HandRequest.HandCard cards = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCards()
    {
        return $this->cards;
    }

    /**
     * Generated from protobuf field <code>repeated .PokerHands.HandRequest.HandCard cards = 1;</code>
     * @param \PokerHands\HandRequest\HandCard[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCards($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \PokerHands\HandRequest\HandCard::class);
        $this->cards = $arr;

        return $this;
    }

}

