<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokerhands.proto

namespace PokerHands;

if (false) {
    /**
     * This class is deprecated. Use PokerHands\HandRequest\HandCard\Rank instead.
     * @deprecated
     */
    class HandRequest_HandCard_Rank {}
}
class_exists(HandRequest\HandCard\Rank::class);
@trigger_error('PokerHands\HandRequest_HandCard_Rank is deprecated and will be removed in the next major release. Use PokerHands\HandRequest\HandCard\Rank instead', E_USER_DEPRECATED);

