<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokerhands.proto

namespace PokerHands;

if (false) {
    /**
     * This class is deprecated. Use PokerHands\HandRequest\HandCard instead.
     * @deprecated
     */
    class HandRequest_HandCard {}
}
class_exists(HandRequest\HandCard::class);
@trigger_error('PokerHands\HandRequest_HandCard is deprecated and will be removed in the next major release. Use PokerHands\HandRequest\HandCard instead', E_USER_DEPRECATED);

