<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokerhands.proto

namespace PokerHands;

if (false) {
    /**
     * This class is deprecated. Use PokerHands\HandRequest\HandCard\Suit instead.
     * @deprecated
     */
    class HandRequest_HandCard_Suit {}
}
class_exists(HandRequest\HandCard\Suit::class);
@trigger_error('PokerHands\HandRequest_HandCard_Suit is deprecated and will be removed in the next major release. Use PokerHands\HandRequest\HandCard\Suit instead', E_USER_DEPRECATED);

