<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokerhands.proto

namespace PokerHands\BestHandResult\ResultCard;

/**
 * Protobuf type <code>PokerHands.BestHandResult.ResultCard.Suit</code>
 */
class Suit
{
    /**
     * Generated from protobuf enum <code>HEARTS = 0;</code>
     */
    const HEARTS = 0;
    /**
     * Generated from protobuf enum <code>DIAMONDS = 1;</code>
     */
    const DIAMONDS = 1;
    /**
     * Generated from protobuf enum <code>CLUBS = 2;</code>
     */
    const CLUBS = 2;
    /**
     * Generated from protobuf enum <code>SPADES = 3;</code>
     */
    const SPADES = 3;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Suit::class, \PokerHands\BestHandResult_ResultCard_Suit::class);

