<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokerhands.proto

namespace PokerHands\BestHandResult;

/**
 * Protobuf type <code>PokerHands.BestHandResult.Category</code>
 */
class Category
{
    /**
     * Generated from protobuf enum <code>ROYAL_FLUSH = 0;</code>
     */
    const ROYAL_FLUSH = 0;
    /**
     * Generated from protobuf enum <code>STRAIGHT_FLUSH = 1;</code>
     */
    const STRAIGHT_FLUSH = 1;
    /**
     * Generated from protobuf enum <code>FOUR_OF_A_KIND = 2;</code>
     */
    const FOUR_OF_A_KIND = 2;
    /**
     * Generated from protobuf enum <code>FULL_HOUSE = 3;</code>
     */
    const FULL_HOUSE = 3;
    /**
     * Generated from protobuf enum <code>FLUSH = 4;</code>
     */
    const FLUSH = 4;
    /**
     * Generated from protobuf enum <code>STRAIGHT = 5;</code>
     */
    const STRAIGHT = 5;
    /**
     * Generated from protobuf enum <code>THREE_OF_A_KIND = 6;</code>
     */
    const THREE_OF_A_KIND = 6;
    /**
     * Generated from protobuf enum <code>TWO_PAIR = 7;</code>
     */
    const TWO_PAIR = 7;
    /**
     * Generated from protobuf enum <code>ONE_PAIR = 8;</code>
     */
    const ONE_PAIR = 8;
    /**
     * Generated from protobuf enum <code>HIGH_CARD = 9;</code>
     */
    const HIGH_CARD = 9;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Category::class, \PokerHands\BestHandResult_Category::class);

