<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voting.proto

namespace Voting\VotingRequest;

/**
 * Protobuf type <code>voting.VotingRequest.Vote</code>
 */
class Vote
{
    /**
     * Generated from protobuf enum <code>UP = 0;</code>
     */
    const UP = 0;
    /**
     * Generated from protobuf enum <code>DOWN = 1;</code>
     */
    const DOWN = 1;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Vote::class, \Voting\VotingRequest_Vote::class);

