<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokerhands.proto

namespace PokerHands\HandRequest\HandCard;

/**
 * Protobuf type <code>PokerHands.HandRequest.HandCard.Rank</code>
 */
class Rank
{
    /**
     * Generated from protobuf enum <code>PADDING = 0;</code>
     */
    const PADDING = 0;
    /**
     * Generated from protobuf enum <code>PBDDING = 1;</code>
     */
    const PBDDING = 1;
    /**
     * Generated from protobuf enum <code>TWO = 2;</code>
     */
    const TWO = 2;
    /**
     * Generated from protobuf enum <code>THREE = 3;</code>
     */
    const THREE = 3;
    /**
     * Generated from protobuf enum <code>FOUR = 4;</code>
     */
    const FOUR = 4;
    /**
     * Generated from protobuf enum <code>FIVE = 5;</code>
     */
    const FIVE = 5;
    /**
     * Generated from protobuf enum <code>SIX = 6;</code>
     */
    const SIX = 6;
    /**
     * Generated from protobuf enum <code>SEVEN = 7;</code>
     */
    const SEVEN = 7;
    /**
     * Generated from protobuf enum <code>EIGHT = 8;</code>
     */
    const EIGHT = 8;
    /**
     * Generated from protobuf enum <code>NINE = 9;</code>
     */
    const NINE = 9;
    /**
     * Generated from protobuf enum <code>TEN = 10;</code>
     */
    const TEN = 10;
    /**
     * Generated from protobuf enum <code>JACK = 11;</code>
     */
    const JACK = 11;
    /**
     * Generated from protobuf enum <code>QUEEN = 12;</code>
     */
    const QUEEN = 12;
    /**
     * Generated from protobuf enum <code>KING = 13;</code>
     */
    const KING = 13;
    /**
     * Generated from protobuf enum <code>ACE = 14;</code>
     */
    const ACE = 14;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Rank::class, \PokerHands\HandRequest_HandCard_Rank::class);

