<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voting.proto

namespace Voting;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>voting.VotingResponse</code>
 */
class VotingResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string confirmation = 1;</code>
     */
    private $confirmation = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $confirmation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Voting::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string confirmation = 1;</code>
     * @return string
     */
    public function getConfirmation()
    {
        return $this->confirmation;
    }

    /**
     * Generated from protobuf field <code>string confirmation = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setConfirmation($var)
    {
        GPBUtil::checkString($var, True);
        $this->confirmation = $var;

        return $this;
    }

}

