<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voting.proto

namespace Voting;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>voting.VotingRequest</code>
 */
class VotingRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string url = 1;</code>
     */
    private $url = '';
    /**
     * Generated from protobuf field <code>.voting.VotingRequest.Vote vote = 2;</code>
     */
    private $vote = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $url
     *     @type int $vote
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Voting::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string url = 1;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.voting.VotingRequest.Vote vote = 2;</code>
     * @return int
     */
    public function getVote()
    {
        return $this->vote;
    }

    /**
     * Generated from protobuf field <code>.voting.VotingRequest.Vote vote = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setVote($var)
    {
        GPBUtil::checkEnum($var, \Voting\VotingRequest_Vote::class);
        $this->vote = $var;

        return $this;
    }

}

