<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voting.proto

namespace Voting;

if (false) {
    /**
     * This class is deprecated. Use Voting\VotingRequest\Vote instead.
     * @deprecated
     */
    class VotingRequest_Vote {}
}
class_exists(VotingRequest\Vote::class);
@trigger_error('Voting\VotingRequest_Vote is deprecated and will be removed in the next major release. Use Voting\VotingRequest\Vote instead', E_USER_DEPRECATED);

