<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voting.proto

namespace GPBMetadata;

class Voting
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae9010a0c766f74696e672e70726f746f1206766f74696e6722600a0d56" .
            "6f74696e6752657175657374120b0a0375726c18012001280912280a0476" .
            "6f746518022001280e321a2e766f74696e672e566f74696e675265717565" .
            "73742e566f746522180a04566f746512060a025550100012080a04444f57" .
            "4e100122260a0e566f74696e67526573706f6e736512140a0c636f6e6669" .
            "726d6174696f6e180120012809323f0a06566f74696e6712350a04566f74" .
            "6512152e766f74696e672e566f74696e67526571756573741a162e766f74" .
            "696e672e566f74696e67526573706f6e7365620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

